# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GSMUtility_New.ui'
#
# Created: Sun Jun 12 00:55:36 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(960, 650)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/background/Icons/AIbEiAIAAABECP2Iptyl4PzmnAEiC3ZjYXJkX3Bob3RvKihiMjczYWVlNWQ1ZWVlNjYyY2U2NzA5YWUwNzgzMjE2MmZkMGYxN2Q5MAFyoVXTDsx0nC3OGfmWE7vsTYpe9Q.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(_fromUtf8("QMainWindow{background-image: url(:/background/Icons/background.jpg);background-repeat: repeat;}\n"
"\n"
"QToolBar{background:blue;}\n"
"\n"
"QWidget#scrollArea{background-color: blue;}\n"
"QTabBar::tab { background: darkblue; color: white; padding: 10px; border: 2px solid blue;}\n"
"QTabBar::tab:selected {background: rgb(217, 217, 0);  color: black; }\n"
"QTabBar::tab:!selected {background:darkblue;  color: white;}\n"
"/*QTabBar {background-color: blue;} */\n"
"QTabBar::tab:hover{color:#ccc;    background-color: qlineargradient(spread:pad, x1:0.517, y1:0, x2:0.517, y2:1, stop:0 rgba(45, 45, 45, 255), stop:0.505682 rgba(45, 45, 45, 255), stop:1 rgba(29, 29, 29, 255));    border-color:#2d89ef;border-width:2px;}\n"
"\n"
"QPushButton{border-style:solid;background-color:darkblue;color:white;border-radius:3px;font: 12pt \"MS Shell Dlg 2\";}\n"
"QPushButton:hover{color:#ccc;    background-color: qlineargradient(spread:pad, x1:0.517, y1:0, x2:0.517, y2:1, stop:0 rgba(45, 45, 45, 255), stop:0.505682 rgba(45, 45, 45, 255), stop:1 rgba(29, 29, 29, 255));    border-color:#2d89ef;border-width:2px;}\n"
"QPushButton:pressed{background-color: lightblue;}\n"
"QPushButton:disabled{background-color: rgb(176, 176, 176);}\n"
"\n"
"QPushButton#connectButton{ background-color: darkred;}\n"
"QPushButton#connectButton:hover{color:#ccc;    background-color: qlineargradient(spread:pad, x1:0.517, y1:0, x2:0.517, y2:1, stop:0 rgba(45, 45, 45, 255), stop:0.505682 rgba(45, 45, 45, 255), stop:1 rgba(29, 29, 29, 255));    border-color:#2d89ef;border-width:2px;}\n"
"QPushButton#connectButton:pressed{background-color: lightblue;}\n"
"QPushButton#connectButton:disabled{background-color: rgb(176, 176, 176);}\n"
"\n"
"QComboBox{border-style:solid;background-color:darkblue;color:white;border-radius:3px;font: 12pt \"MS Shell Dlg 2\"; padding: 10px}\n"
"QComboBox:hover{color:#ccc;    background-color: qlineargradient(spread:pad, x1:0.517, y1:0, x2:0.517, y2:1, stop:0 rgba(45, 45, 45, 255), stop:0.505682 rgba(45, 45, 45, 255), stop:1 rgba(29, 29, 29, 255));    border-color:#2d89ef;border-width:2px;}\n"
"QComboBox:pressed{background-color: lightblue;}\n"
"\n"
"QLineEdit {border:4px outset; border-radius: 8px; border-color: blue; color:rgb(0, 0, 0);  background-color: rgb(235, 235, 235); padding:10px;font: 75 12pt \"MS Shell Dlg 2\";}\n"
"/*QLineEdit { border-radius: 8px;  color:black;background-color: white; } */\n"
"QLineEdit:focus {  border:4px outset; border-radius: 8px; border-color: rgb(41, 237, 215); color:rgb(0, 0, 0);  background-color: rgb(240, 204, 204); }\n"
"\n"
"QLabel {border:4px outset; border-radius: 0px; border-color: blue; color:white;  background-color: darkblue; padding:5px;font: 75 12pt \"MS Shell Dlg 2\";}\n"
"QPlainTextEdit {border:4px outset; border-radius: 0px; border-color: blue; color:black;  background-color: rgb(235, 235, 235);; padding:5px;font: 75 12pt \"MS Shell Dlg 2\";}"))
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_5 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_5.addWidget(self.label, 0, 2, 1, 1)
        self.pushButton_6 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.gridLayout_5.addWidget(self.pushButton_6, 1, 2, 1, 1)
        self.SerialConsole = QtGui.QPlainTextEdit(self.centralwidget)
        self.SerialConsole.setEnabled(True)
        self.SerialConsole.setMinimumSize(QtCore.QSize(300, 0))
        self.SerialConsole.setReadOnly(True)
        self.SerialConsole.setObjectName(_fromUtf8("SerialConsole"))
        self.gridLayout_5.addWidget(self.SerialConsole, 2, 2, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(200, 50))
        self.tabWidget.setMouseTracking(True)
        self.tabWidget.setToolTip(_fromUtf8(""))
        self.tabWidget.setStatusTip(_fromUtf8(""))
        self.tabWidget.setWhatsThis(_fromUtf8(""))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet(_fromUtf8("QMainWindow{background-image: url(:/Background/Icons/background.jpg);}\n"
"\n"
"QToolBar{background:blue;}\n"
"\n"
"QWidget#tabWidget{background-color: blue;}\n"
"QTabBar::tab { background: darkblue; color: white; padding: 10px; border: 2px solid blue;}\n"
"QTabBar::tab:selected {background: rgb(217, 217, 0);  color: black; }\n"
"QTabBar::tab:!selected {background:darkblue;  color: white;}\n"
"/*QTabBar {background-color: blue;} */\n"
"QTabBar::tab:hover{color:#ccc;    background-color: qlineargradient(spread:pad, x1:0.517, y1:0, x2:0.517, y2:1, stop:0 rgba(45, 45, 45, 255), stop:0.505682 rgba(45, 45, 45, 255), stop:1 rgba(29, 29, 29, 255));    border-color:#2d89ef;border-width:2px;}\n"
"\n"
"QPushButton{border-style:solid;background-color:darkblue;color:white;border-radius:3px;font: 12pt \"MS Shell Dlg 2\";}\n"
"QPushButton:hover{color:#ccc;    background-color: qlineargradient(spread:pad, x1:0.517, y1:0, x2:0.517, y2:1, stop:0 rgba(45, 45, 45, 255), stop:0.505682 rgba(45, 45, 45, 255), stop:1 rgba(29, 29, 29, 255));    border-color:#2d89ef;border-width:2px;}\n"
"QPushButton:pressed{background-color: lightblue;}\n"
"QPushButton:disabled{background-color: rgb(176, 176, 176);}\n"
"\n"
"QPushButton#connectButton{ background-color: darkred;}\n"
"QPushButton#connectButton:hover{color:#ccc;    background-color: qlineargradient(spread:pad, x1:0.517, y1:0, x2:0.517, y2:1, stop:0 rgba(45, 45, 45, 255), stop:0.505682 rgba(45, 45, 45, 255), stop:1 rgba(29, 29, 29, 255));    border-color:#2d89ef;border-width:2px;}\n"
"QPushButton#connectButton:pressed{background-color: lightblue;}\n"
"QPushButton#connectButton:disabled{background-color: rgb(176, 176, 176);}\n"
"\n"
"QComboBox{border-style:solid;background-color:darkblue;color:white;border-radius:3px;font: 12pt \"MS Shell Dlg 2\"; padding: 10px}\n"
"QComboBox:hover{color:#ccc;    background-color: qlineargradient(spread:pad, x1:0.517, y1:0, x2:0.517, y2:1, stop:0 rgba(45, 45, 45, 255), stop:0.505682 rgba(45, 45, 45, 255), stop:1 rgba(29, 29, 29, 255));    border-color:#2d89ef;border-width:2px;}\n"
"QComboBox:pressed{background-color: lightblue;}\n"
"\n"
"QLineEdit {border:4px outset; border-radius: 8px; border-color: blue; color:rgb(0, 0, 0);  background-color: rgb(235, 235, 235); padding:10px;font: 75 12pt \"MS Shell Dlg 2\";}\n"
"/*QLineEdit { border-radius: 8px;  color:black;background-color: white; } */\n"
"QLineEdit:focus {  border:4px outset; border-radius: 8px; border-color: rgb(41, 237, 215); color:rgb(0, 0, 0);  background-color: rgb(240, 204, 204); }\n"
"\n"
"QLabel {border:4px outset; border-radius: 0px; border-color: blue; color:white;  background-color: darkblue; padding:5px;font: 75 12pt \"MS Shell Dlg 2\";}\n"
"QPlainTextEdit {border:4px outset; border-radius: 0px; border-color: blue; color:black;  background-color: rgb(235, 235, 235);; padding:5px;font: 75 12pt \"MS Shell Dlg 2\";}"))
        self.tabWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tabWidget.setIconSize(QtCore.QSize(40, 40))
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.settingsTab = QtGui.QWidget()
        self.settingsTab.setObjectName(_fromUtf8("settingsTab"))
        self.gridLayout = QtGui.QGridLayout(self.settingsTab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 5, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 60, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 3, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 6, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 5, 2, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(132, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 5, 4, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 2, 4, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(10, 10, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 2, 2, 1, 1)
        self.findButton = QtGui.QPushButton(self.settingsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.findButton.sizePolicy().hasHeightForWidth())
        self.findButton.setSizePolicy(sizePolicy)
        self.findButton.setMinimumSize(QtCore.QSize(200, 50))
        self.findButton.setMaximumSize(QtCore.QSize(200, 50))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/Icons/find.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.findButton.setIcon(icon1)
        self.findButton.setIconSize(QtCore.QSize(32, 32))
        self.findButton.setObjectName(_fromUtf8("findButton"))
        self.gridLayout.addWidget(self.findButton, 2, 3, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(10, 10, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 2, 0, 1, 1)
        self.portComboBox = QtGui.QComboBox(self.settingsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portComboBox.sizePolicy().hasHeightForWidth())
        self.portComboBox.setSizePolicy(sizePolicy)
        self.portComboBox.setMinimumSize(QtCore.QSize(200, 50))
        self.portComboBox.setMaximumSize(QtCore.QSize(200, 50))
        self.portComboBox.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContentsOnFirstShow)
        self.portComboBox.setObjectName(_fromUtf8("portComboBox"))
        self.gridLayout.addWidget(self.portComboBox, 2, 1, 1, 1)
        self.baudcomboBox = QtGui.QComboBox(self.settingsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baudcomboBox.sizePolicy().hasHeightForWidth())
        self.baudcomboBox.setSizePolicy(sizePolicy)
        self.baudcomboBox.setMinimumSize(QtCore.QSize(200, 50))
        self.baudcomboBox.setMaximumSize(QtCore.QSize(200, 50))
        self.baudcomboBox.setObjectName(_fromUtf8("baudcomboBox"))
        self.baudcomboBox.addItem(_fromUtf8(""))
        self.baudcomboBox.addItem(_fromUtf8(""))
        self.baudcomboBox.addItem(_fromUtf8(""))
        self.baudcomboBox.addItem(_fromUtf8(""))
        self.baudcomboBox.addItem(_fromUtf8(""))
        self.baudcomboBox.addItem(_fromUtf8(""))
        self.baudcomboBox.addItem(_fromUtf8(""))
        self.baudcomboBox.addItem(_fromUtf8(""))
        self.baudcomboBox.addItem(_fromUtf8(""))
        self.baudcomboBox.addItem(_fromUtf8(""))
        self.baudcomboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.baudcomboBox, 5, 1, 1, 1)
        self.connectButton = QtGui.QPushButton(self.settingsTab)
        self.connectButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.connectButton.sizePolicy().hasHeightForWidth())
        self.connectButton.setSizePolicy(sizePolicy)
        self.connectButton.setMinimumSize(QtCore.QSize(200, 50))
        self.connectButton.setMaximumSize(QtCore.QSize(200, 50))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/Icons/connect.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.connectButton.setIcon(icon2)
        self.connectButton.setIconSize(QtCore.QSize(32, 32))
        self.connectButton.setObjectName(_fromUtf8("connectButton"))
        self.gridLayout.addWidget(self.connectButton, 5, 3, 1, 1)
        self.tabWidget.addTab(self.settingsTab, _fromUtf8(""))
        self.scriptTab = QtGui.QWidget()
        self.scriptTab.setObjectName(_fromUtf8("scriptTab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.scriptTab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem9 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 1, 2, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem10, 1, 4, 1, 1)
        self.SendButton = QtGui.QPushButton(self.scriptTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SendButton.sizePolicy().hasHeightForWidth())
        self.SendButton.setSizePolicy(sizePolicy)
        self.SendButton.setMinimumSize(QtCore.QSize(100, 50))
        self.SendButton.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 0);"))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/Icons/running_man.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SendButton.setIcon(icon3)
        self.SendButton.setIconSize(QtCore.QSize(32, 32))
        self.SendButton.setObjectName(_fromUtf8("SendButton"))
        self.gridLayout_2.addWidget(self.SendButton, 1, 3, 1, 1)
        self.ScriptLineEdit = QtGui.QLineEdit(self.scriptTab)
        self.ScriptLineEdit.setMinimumSize(QtCore.QSize(250, 50))
        self.ScriptLineEdit.setText(_fromUtf8(""))
        self.ScriptLineEdit.setObjectName(_fromUtf8("ScriptLineEdit"))
        self.gridLayout_2.addWidget(self.ScriptLineEdit, 1, 1, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem11, 1, 0, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem12, 0, 1, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem13, 2, 1, 1, 1)
        self.tabWidget.addTab(self.scriptTab, _fromUtf8(""))
        self.callTab = QtGui.QWidget()
        self.callTab.setObjectName(_fromUtf8("callTab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.callTab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem14, 2, 3, 1, 1)
        self.Call_Button = QtGui.QPushButton(self.callTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Call_Button.sizePolicy().hasHeightForWidth())
        self.Call_Button.setSizePolicy(sizePolicy)
        self.Call_Button.setMinimumSize(QtCore.QSize(100, 50))
        self.Call_Button.setMaximumSize(QtCore.QSize(100, 50))
        self.Call_Button.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 0);"))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/Icons/unnamed.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Call_Button.setIcon(icon4)
        self.Call_Button.setIconSize(QtCore.QSize(40, 40))
        self.Call_Button.setObjectName(_fromUtf8("Call_Button"))
        self.gridLayout_3.addWidget(self.Call_Button, 1, 3, 1, 1)
        self.Halt_Button = QtGui.QPushButton(self.callTab)
        self.Halt_Button.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Halt_Button.sizePolicy().hasHeightForWidth())
        self.Halt_Button.setSizePolicy(sizePolicy)
        self.Halt_Button.setMinimumSize(QtCore.QSize(100, 50))
        self.Halt_Button.setMaximumSize(QtCore.QSize(100, 50))
        self.Halt_Button.setStyleSheet(_fromUtf8("background-color: rgb(170, 0, 0);"))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/Icons/unnamed (1).png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Halt_Button.setIcon(icon5)
        self.Halt_Button.setIconSize(QtCore.QSize(32, 32))
        self.Halt_Button.setObjectName(_fromUtf8("Halt_Button"))
        self.gridLayout_3.addWidget(self.Halt_Button, 3, 3, 1, 1)
        self.NumberlineEdit = QtGui.QLineEdit(self.callTab)
        self.NumberlineEdit.setMinimumSize(QtCore.QSize(100, 50))
        self.NumberlineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.NumberlineEdit.setMouseTracking(True)
        self.NumberlineEdit.setAcceptDrops(False)
        self.NumberlineEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.NumberlineEdit.setText(_fromUtf8(""))
        self.NumberlineEdit.setMaxLength(32767)
        self.NumberlineEdit.setFrame(True)
        self.NumberlineEdit.setEchoMode(QtGui.QLineEdit.Normal)
        self.NumberlineEdit.setCursorPosition(0)
        self.NumberlineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.NumberlineEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.NumberlineEdit.setProperty("Count", 0)
        self.NumberlineEdit.setObjectName(_fromUtf8("NumberlineEdit"))
        self.gridLayout_3.addWidget(self.NumberlineEdit, 1, 1, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem15, 1, 2, 1, 1)
        spacerItem16 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem16, 1, 0, 1, 1)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem17, 1, 4, 1, 1)
        spacerItem18 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem18, 4, 3, 1, 1)
        spacerItem19 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem19, 0, 3, 1, 1)
        self.tabWidget.addTab(self.callTab, _fromUtf8(""))
        self.smsTab = QtGui.QWidget()
        self.smsTab.setObjectName(_fromUtf8("smsTab"))
        self.pushButton_4 = QtGui.QPushButton(self.smsTab)
        self.pushButton_4.setGeometry(QtCore.QRect(360, 60, 100, 50))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(100, 50))
        self.pushButton_4.setMaximumSize(QtCore.QSize(100, 50))
        self.pushButton_4.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 0);"))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/Icons/Telegram (1).png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon6)
        self.pushButton_4.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.lineEdit_3 = QtGui.QLineEdit(self.smsTab)
        self.lineEdit_3.setGeometry(QtCore.QRect(50, 60, 261, 50))
        self.lineEdit_3.setMinimumSize(QtCore.QSize(100, 50))
        self.lineEdit_3.setStatusTip(_fromUtf8(""))
        self.lineEdit_3.setText(_fromUtf8(""))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.label_6 = QtGui.QLabel(self.smsTab)
        self.label_6.setGeometry(QtCore.QRect(30, 120, 201, 41))
        self.label_6.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lineEdit = QtGui.QLineEdit(self.smsTab)
        self.lineEdit.setGeometry(QtCore.QRect(240, 120, 71, 51))
        self.lineEdit.setMaxLength(160)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.lineEdit_12 = QtGui.QLineEdit(self.smsTab)
        self.lineEdit_12.setGeometry(QtCore.QRect(50, 170, 261, 71))
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.tabWidget.addTab(self.smsTab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(-10, 160, 151, 41))
        self.label_2.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.pushButton_3 = QtGui.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(170, 420, 131, 41))
        self.pushButton_3.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 0);"))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_5 = QtGui.QPushButton(self.tab_2)
        self.pushButton_5.setGeometry(QtCore.QRect(390, 420, 121, 41))
        self.pushButton_5.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 0);"))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.plainTextEdit_2 = QtGui.QPlainTextEdit(self.tab_2)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(150, 150, 381, 51))
        self.plainTextEdit_2.setObjectName(_fromUtf8("plainTextEdit_2"))
        self.plainTextEdit_3 = QtGui.QPlainTextEdit(self.tab_2)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(150, 220, 381, 191))
        self.plainTextEdit_3.setObjectName(_fromUtf8("plainTextEdit_3"))
        self.lineEdit_16 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_16.setGeometry(QtCore.QRect(150, 90, 381, 51))
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.label_14 = QtGui.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(10, 90, 121, 51))
        self.label_14.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);"))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.pushButton_26 = QtGui.QPushButton(self.tab_2)
        self.pushButton_26.setGeometry(QtCore.QRect(360, 20, 131, 41))
        self.pushButton_26.setStyleSheet(_fromUtf8("background-color: rgb(170, 0, 0);"))
        self.pushButton_26.setObjectName(_fromUtf8("pushButton_26"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.label_3 = QtGui.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(110, 120, 101, 51))
        self.label_3.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.tab_3)
        self.label_4.setGeometry(QtCore.QRect(140, 190, 71, 41))
        self.label_4.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.tab_3)
        self.label_5.setGeometry(QtCore.QRect(90, 50, 121, 61))
        self.label_5.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);"))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.pushButton_7 = QtGui.QPushButton(self.tab_3)
        self.pushButton_7.setGeometry(QtCore.QRect(250, 250, 131, 41))
        self.pushButton_7.setStyleSheet(_fromUtf8("background-color: rgb(170, 0, 0);"))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.lineEdit_2 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_2.setGeometry(QtCore.QRect(220, 60, 321, 51))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit_4 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_4.setGeometry(QtCore.QRect(220, 120, 241, 51))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.lineEdit_5 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_5.setGeometry(QtCore.QRect(220, 180, 113, 51))
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.pushButton_8 = QtGui.QPushButton(self.tab_3)
        self.pushButton_8.setGeometry(QtCore.QRect(60, 250, 131, 41))
        self.pushButton_8.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 0);"))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.groupBox = QtGui.QGroupBox(self.tab_3)
        self.groupBox.setGeometry(QtCore.QRect(0, 310, 491, 211))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.plainTextEdit_7 = QtGui.QPlainTextEdit(self.groupBox)
        self.plainTextEdit_7.setGeometry(QtCore.QRect(10, 40, 481, 101))
        self.plainTextEdit_7.setObjectName(_fromUtf8("plainTextEdit_7"))
        self.pushButton_25 = QtGui.QPushButton(self.groupBox)
        self.pushButton_25.setGeometry(QtCore.QRect(180, 150, 111, 51))
        self.pushButton_25.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 0);"))
        self.pushButton_25.setObjectName(_fromUtf8("pushButton_25"))
        self.comboBox = QtGui.QComboBox(self.tab_3)
        self.comboBox.setGeometry(QtCore.QRect(220, 10, 131, 41))
        self.comboBox.setStyleSheet(_fromUtf8("\n"
"border-color: rgba(255, 255, 255, 0);"))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.label_7 = QtGui.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 201, 41))
        self.label_7.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);"))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.scrollArea = QtGui.QScrollArea(self.tab_4)
        self.scrollArea.setStyleSheet(_fromUtf8("QScrollArea { background: transparent; }\n"
"QScrollArea > QWidget > QWidget { background: transparent; }"))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 563, 555))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_8 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_9 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);"))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_8.addWidget(self.label_9, 1, 0, 1, 1)
        self.lineEdit_6 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.gridLayout_8.addWidget(self.lineEdit_6, 1, 1, 1, 1)
        self.lineEdit_7 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.gridLayout_8.addWidget(self.lineEdit_7, 2, 1, 1, 1)
        self.lineEdit_11 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.gridLayout_8.addWidget(self.lineEdit_11, 0, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);"))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_8.addWidget(self.label_8, 0, 0, 1, 1)
        self.lineEdit_9 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.gridLayout_8.addWidget(self.lineEdit_9, 7, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);"))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_8.addWidget(self.label_11, 4, 0, 1, 1)
        self.lineEdit_8 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.gridLayout_8.addWidget(self.lineEdit_8, 4, 1, 1, 1)
        self.lineEdit_10 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.gridLayout_8.addWidget(self.lineEdit_10, 8, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);"))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_8.addWidget(self.label_12, 7, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);"))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_8.addWidget(self.label_13, 8, 0, 1, 1)
        self.plainTextEdit_4 = QtGui.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.plainTextEdit_4.setObjectName(_fromUtf8("plainTextEdit_4"))
        self.gridLayout_8.addWidget(self.plainTextEdit_4, 9, 0, 3, 2)
        self.pushButton_10 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_10.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 0);"))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.gridLayout_8.addWidget(self.pushButton_10, 12, 0, 1, 1)
        self.pushButton_9 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_9.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 0);"))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.gridLayout_8.addWidget(self.pushButton_9, 12, 1, 1, 1, QtCore.Qt.AlignRight)
        self.widget = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_6 = QtGui.QGridLayout(self.widget)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.pushButton_11 = QtGui.QPushButton(self.widget)
        self.pushButton_11.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_11.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_11.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 0);"))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/Icons/connect-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon7)
        self.pushButton_11.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.gridLayout_6.addWidget(self.pushButton_11, 0, 0, 2, 1)
        self.pushButton_12 = QtGui.QPushButton(self.widget)
        self.pushButton_12.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_12.setStyleSheet(_fromUtf8("background-color: rgb(170, 0, 0);"))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/Icons/45420.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_12.setIcon(icon8)
        self.pushButton_12.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.gridLayout_6.addWidget(self.pushButton_12, 0, 1, 2, 1)
        self.gridLayout_8.addWidget(self.widget, 6, 1, 1, 1, QtCore.Qt.AlignTop)
        self.label_10 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);"))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_8.addWidget(self.label_10, 2, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_7.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.gridLayout_5.addWidget(self.tabWidget, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setCheckable(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon9)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionNew = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/New.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon10)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Elementz_GSM_Utility", None))
        self.label.setText(_translate("MainWindow", "Serial Terminal", None))
        self.pushButton_6.setText(_translate("MainWindow", "Clear Log", None))
        self.SerialConsole.setToolTip(_translate("MainWindow", "Serial Console is readonly!!", None))
        self.SerialConsole.setPlainText(_translate("MainWindow", "Serial Console", None))
        self.findButton.setText(_translate("MainWindow", "Find Port", None))
        self.portComboBox.setToolTip(_translate("MainWindow", "Select COM Port", None))
        self.baudcomboBox.setToolTip(_translate("MainWindow", "Select BAUD Rate", None))
        self.baudcomboBox.setItemText(0, _translate("MainWindow", "SELECT", None))
        self.baudcomboBox.setItemText(1, _translate("MainWindow", "300", None))
        self.baudcomboBox.setItemText(2, _translate("MainWindow", "600", None))
        self.baudcomboBox.setItemText(3, _translate("MainWindow", "1200", None))
        self.baudcomboBox.setItemText(4, _translate("MainWindow", "2400", None))
        self.baudcomboBox.setItemText(5, _translate("MainWindow", "4800", None))
        self.baudcomboBox.setItemText(6, _translate("MainWindow", "9600", None))
        self.baudcomboBox.setItemText(7, _translate("MainWindow", "19200", None))
        self.baudcomboBox.setItemText(8, _translate("MainWindow", "38400", None))
        self.baudcomboBox.setItemText(9, _translate("MainWindow", "57600", None))
        self.baudcomboBox.setItemText(10, _translate("MainWindow", "115200", None))
        self.connectButton.setText(_translate("MainWindow", "Connect", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settingsTab), _translate("MainWindow", "Settings", None))
        self.SendButton.setText(_translate("MainWindow", "Execute", None))
        self.ScriptLineEdit.setToolTip(_translate("MainWindow", "Type AT command and press Send Button, eg: AT+CSQ", None))
        self.ScriptLineEdit.setPlaceholderText(_translate("MainWindow", "Eg: AT+CSQ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.scriptTab), _translate("MainWindow", "Geek Mode", None))
        self.Call_Button.setText(_translate("MainWindow", "Call", None))
        self.Halt_Button.setText(_translate("MainWindow", "End Call", None))
        self.NumberlineEdit.setToolTip(_translate("MainWindow", "Type phone number and press Call, eg: 09495XXXXXX", None))
        self.NumberlineEdit.setPlaceholderText(_translate("MainWindow", "EX:944XXXXXXXX", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.callTab), _translate("MainWindow", "Call", None))
        self.pushButton_4.setText(_translate("MainWindow", "Send", None))
        self.lineEdit_3.setToolTip(_translate("MainWindow", "Enter phone number, Write message below and Press Send button", None))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Eg: 9495XXXXXX", None))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" color:#ff0000;\">No of Character Entered :</span></p></body></html>", None))
        self.lineEdit_12.setPlaceholderText(_translate("MainWindow", "Try not to Exceed 160 Character", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.smsTab), _translate("MainWindow", "SMS", None))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">Source Address :</span></p></body></html>", None))
        self.pushButton_3.setText(_translate("MainWindow", "Get", None))
        self.pushButton_5.setText(_translate("MainWindow", "Post", None))
        self.lineEdit_16.setPlaceholderText(_translate("MainWindow", "No Need to Type if You Have Already Typed", None))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\"> APN Name :</span></p></body></html>", None))
        self.pushButton_26.setText(_translate("MainWindow", "Close Session", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "http", None))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">Server IP :</span></p></body></html>", None))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">Port :</span></p></body></html>", None))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">APN Name :</span></p></body></html>", None))
        self.pushButton_7.setText(_translate("MainWindow", "Disconnect", None))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "No Need to Type If u have already typed", None))
        self.pushButton_8.setText(_translate("MainWindow", "Connect", None))
        self.groupBox.setTitle(_translate("MainWindow", "Send Data", None))
        self.plainTextEdit_7.setPlainText(_translate("MainWindow", "Type ur message here", None))
        self.pushButton_25.setText(_translate("MainWindow", "Send", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "Select", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "TCP", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "UDP", None))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">Choose your Preferance :</span></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "TCP/ UDP", None))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" color:#ff0000;\">FTP Server :</span></p></body></html>", None))
        self.lineEdit_11.setPlaceholderText(_translate("MainWindow", "Already Typed?No Need To Type Again", None))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" color:#ff0000;\">APN Name :</span></p></body></html>", None))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" color:#ff0000;\">Password :</span></p></body></html>", None))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" color:#ff0000;\">File Name :</span></p></body></html>", None))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" color:#ff0000;\">Directry :</span></p></body></html>", None))
        self.plainTextEdit_4.setPlainText(_translate("MainWindow", "Caution: As the Push data Size varies carrier to Carrier It is advisable to Push small data at a time. (10bytes is prefarable)", None))
        self.pushButton_10.setText(_translate("MainWindow", "FTP Get", None))
        self.pushButton_9.setText(_translate("MainWindow", "FTP Push", None))
        self.pushButton_11.setText(_translate("MainWindow", "Connect", None))
        self.pushButton_12.setText(_translate("MainWindow", "Disconnect", None))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" color:#ff0000;\">Username :</span></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "FTP", None))
        self.actionSave.setText(_translate("MainWindow", "&Save", None))
        self.actionSave.setToolTip(_translate("MainWindow", "Save", None))
        self.actionNew.setText(_translate("MainWindow", "&New", None))
        self.actionOpen.setText(_translate("MainWindow", "&Open", None))

import background_rc
