# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GSMUtility.ui'
#
# Created: Sun Jun 26 01:25:43 2016
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(776, 479)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/background/Icons/AIbEiAIAAABECP2Iptyl4PzmnAEiC3ZjYXJkX3Bob3RvKihiMjczYWVlNWQ1ZWVlNjYyY2U2NzA5YWUwNzgzMjE2MmZkMGYxN2Q5MAFyoVXTDsx0nC3OGfmWE7vsTYpe9Q.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(_fromUtf8("QMainWindow{background-image: url(:/background/Icons/background.png);background-repeat: repeat;}\n"
"\n"
"QToolBar{background:blue;}\n"
"\n"
"QWidget#scrollArea{background-color: blue;}\n"
"QTabBar::tab { background: darkblue; color: white; padding: 10px; border: 2px solid blue;}\n"
"QTabBar::tab:selected {background: rgb(217, 217, 0);  color: black; }\n"
"QTabBar::tab:!selected {background:darkblue;  color: white;}\n"
"/*QTabBar {background-color: blue;} */\n"
"QTabBar::tab:hover{color:#ccc;    background-color: qlineargradient(spread:pad, x1:0.517, y1:0, x2:0.517, y2:1, stop:0 rgba(45, 45, 45, 255), stop:0.505682 rgba(45, 45, 45, 255), stop:1 rgba(29, 29, 29, 255));    border-color:#2d89ef;border-width:2px;}\n"
"\n"
"QPushButton{border-style:solid;background-color:darkblue;color:white;border-radius:3px;font: 12pt \"MS Shell Dlg 2\";}\n"
"QPushButton:hover{color:#ccc;    background-color: qlineargradient(spread:pad, x1:0.517, y1:0, x2:0.517, y2:1, stop:0 rgba(45, 45, 45, 255), stop:0.505682 rgba(45, 45, 45, 255), stop:1 rgba(29, 29, 29, 255));    border-color:#2d89ef;border-width:2px;}\n"
"QPushButton:pressed{background-color: lightblue;}\n"
"QPushButton:disabled{background-color: rgb(176, 176, 176);}\n"
"\n"
"QPushButton#connectButton{ background-color: darkred;}\n"
"QPushButton#connectButton:hover{color:#ccc;    background-color: qlineargradient(spread:pad, x1:0.517, y1:0, x2:0.517, y2:1, stop:0 rgba(45, 45, 45, 255), stop:0.505682 rgba(45, 45, 45, 255), stop:1 rgba(29, 29, 29, 255));    border-color:#2d89ef;border-width:2px;}\n"
"QPushButton#connectButton:pressed{background-color: lightblue;}\n"
"QPushButton#connectButton:disabled{background-color: rgb(176, 176, 176);}\n"
"\n"
"QComboBox{border-style:solid;background-color:darkblue;color:white;border-radius:3px;font: 12pt \"MS Shell Dlg 2\"; padding: 10px}\n"
"QComboBox:hover{color:#ccc;    background-color: qlineargradient(spread:pad, x1:0.517, y1:0, x2:0.517, y2:1, stop:0 rgba(45, 45, 45, 255), stop:0.505682 rgba(45, 45, 45, 255), stop:1 rgba(29, 29, 29, 255));    border-color:#2d89ef;border-width:2px;}\n"
"QComboBox:pressed{background-color: lightblue;}\n"
"\n"
"QLineEdit {border:4px outset; border-radius: 8px; border-color: blue; color:rgb(0, 0, 0);  background-color: rgb(235, 235, 235); padding:10px;font: 75 12pt \"MS Shell Dlg 2\";}\n"
"/*QLineEdit { border-radius: 8px;  color:black;background-color: white; } */\n"
"QLineEdit:focus {  border:4px outset; border-radius: 8px; border-color: rgb(41, 237, 215); color:rgb(0, 0, 0);  background-color: rgb(240, 204, 204); }\n"
"\n"
"QLabel {border:4px outset; border-radius: 0px; border-color: blue; color:white;  background-color: darkblue; padding:5px;font: 75 12pt \"MS Shell Dlg 2\";}\n"
"QPlainTextEdit {border:4px outset; border-radius: 0px; border-color: blue; color:black;  background-color: rgb(235, 235, 235);; padding:5px;font: 75 12pt \"MS Shell Dlg 2\";}"))
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_5 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.pushButton_6 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.gridLayout_5.addWidget(self.pushButton_6, 1, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 2, 0, 1, 1)
        self.SerialConsole = QtGui.QPlainTextEdit(self.centralwidget)
        self.SerialConsole.setEnabled(True)
        self.SerialConsole.setMinimumSize(QtCore.QSize(300, 0))
        self.SerialConsole.setReadOnly(True)
        self.SerialConsole.setObjectName(_fromUtf8("SerialConsole"))
        self.gridLayout_5.addWidget(self.SerialConsole, 2, 3, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_5.addWidget(self.label, 0, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 2, 2, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(200, 50))
        self.tabWidget.setMouseTracking(True)
        self.tabWidget.setToolTip(_fromUtf8(""))
        self.tabWidget.setStatusTip(_fromUtf8(""))
        self.tabWidget.setWhatsThis(_fromUtf8(""))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet(_fromUtf8("QMainWindow{background-image: url(:/Background/Icons/background.jpg);}\n"
"\n"
"QToolBar{background:blue;}\n"
"\n"
"QWidget#tabWidget{background-color: blue;}\n"
"QTabBar::tab { background: darkblue; color: white; padding: 10px; border: 2px solid blue;}\n"
"QTabBar::tab:selected {background: rgb(217, 217, 0);  color: black; }\n"
"QTabBar::tab:!selected {background:darkblue;  color: white;}\n"
"/*QTabBar {background-color: blue;} */\n"
"QTabBar::tab:hover{color:#ccc;    background-color: qlineargradient(spread:pad, x1:0.517, y1:0, x2:0.517, y2:1, stop:0 rgba(45, 45, 45, 255), stop:0.505682 rgba(45, 45, 45, 255), stop:1 rgba(29, 29, 29, 255));    border-color:#2d89ef;border-width:2px;}\n"
"\n"
"QPushButton{border-style:solid;background-color:darkblue;color:white;border-radius:3px;font: 12pt \"MS Shell Dlg 2\";}\n"
"QPushButton:hover{color:#ccc;    background-color: qlineargradient(spread:pad, x1:0.517, y1:0, x2:0.517, y2:1, stop:0 rgba(45, 45, 45, 255), stop:0.505682 rgba(45, 45, 45, 255), stop:1 rgba(29, 29, 29, 255));    border-color:#2d89ef;border-width:2px;}\n"
"QPushButton:pressed{background-color: lightblue;}\n"
"QPushButton:disabled{background-color: rgb(176, 176, 176);}\n"
"\n"
"QPushButton#connectButton{ background-color: darkred;}\n"
"QPushButton#connectButton:hover{color:#ccc;    background-color: qlineargradient(spread:pad, x1:0.517, y1:0, x2:0.517, y2:1, stop:0 rgba(45, 45, 45, 255), stop:0.505682 rgba(45, 45, 45, 255), stop:1 rgba(29, 29, 29, 255));    border-color:#2d89ef;border-width:2px;}\n"
"QPushButton#connectButton:pressed{background-color: lightblue;}\n"
"QPushButton#connectButton:disabled{background-color: rgb(176, 176, 176);}\n"
"\n"
"QComboBox{border-style:solid;background-color:darkblue;color:white;border-radius:3px;font: 12pt \"MS Shell Dlg 2\"; padding: 10px}\n"
"QComboBox:hover{color:#ccc;    background-color: qlineargradient(spread:pad, x1:0.517, y1:0, x2:0.517, y2:1, stop:0 rgba(45, 45, 45, 255), stop:0.505682 rgba(45, 45, 45, 255), stop:1 rgba(29, 29, 29, 255));    border-color:#2d89ef;border-width:2px;}\n"
"QComboBox:pressed{background-color: lightblue;}\n"
"\n"
"QLineEdit {border:4px outset; border-radius: 8px; border-color: blue; color:rgb(0, 0, 0);  background-color: rgb(235, 235, 235); padding:10px;font: 75 12pt \"MS Shell Dlg 2\";}\n"
"/*QLineEdit { border-radius: 8px;  color:black;background-color: white; } */\n"
"QLineEdit:focus {  border:4px outset; border-radius: 8px; border-color: rgb(41, 237, 215); color:rgb(0, 0, 0);  background-color: rgb(240, 204, 204); }\n"
"\n"
"QLabel {border:4px outset; border-radius: 0px; border-color: blue; color:white;  background-color: darkblue; padding:5px;font: 75 12pt \"MS Shell Dlg 2\";}\n"
"QPlainTextEdit {border:4px outset; border-radius: 0px; border-color: blue; color:black;  background-color: rgb(235, 235, 235);; padding:5px;font: 75 12pt \"MS Shell Dlg 2\";}"))
        self.tabWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tabWidget.setIconSize(QtCore.QSize(40, 40))
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.settingsTab = QtGui.QWidget()
        self.settingsTab.setObjectName(_fromUtf8("settingsTab"))
        self.gridLayout = QtGui.QGridLayout(self.settingsTab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 5, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 60, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 3, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 6, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 5, 2, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(132, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 5, 4, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 2, 4, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(10, 10, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 2, 2, 1, 1)
        self.findButton = QtGui.QPushButton(self.settingsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.findButton.sizePolicy().hasHeightForWidth())
        self.findButton.setSizePolicy(sizePolicy)
        self.findButton.setMinimumSize(QtCore.QSize(200, 50))
        self.findButton.setMaximumSize(QtCore.QSize(200, 50))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/Icons/find.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.findButton.setIcon(icon1)
        self.findButton.setIconSize(QtCore.QSize(32, 32))
        self.findButton.setObjectName(_fromUtf8("findButton"))
        self.gridLayout.addWidget(self.findButton, 2, 3, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(10, 10, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem10, 2, 0, 1, 1)
        self.portComboBox = QtGui.QComboBox(self.settingsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portComboBox.sizePolicy().hasHeightForWidth())
        self.portComboBox.setSizePolicy(sizePolicy)
        self.portComboBox.setMinimumSize(QtCore.QSize(200, 50))
        self.portComboBox.setMaximumSize(QtCore.QSize(200, 50))
        self.portComboBox.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContentsOnFirstShow)
        self.portComboBox.setObjectName(_fromUtf8("portComboBox"))
        self.gridLayout.addWidget(self.portComboBox, 2, 1, 1, 1)
        self.baudcomboBox = QtGui.QComboBox(self.settingsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baudcomboBox.sizePolicy().hasHeightForWidth())
        self.baudcomboBox.setSizePolicy(sizePolicy)
        self.baudcomboBox.setMinimumSize(QtCore.QSize(200, 50))
        self.baudcomboBox.setMaximumSize(QtCore.QSize(200, 50))
        self.baudcomboBox.setObjectName(_fromUtf8("baudcomboBox"))
        self.baudcomboBox.addItem(_fromUtf8(""))
        self.baudcomboBox.addItem(_fromUtf8(""))
        self.baudcomboBox.addItem(_fromUtf8(""))
        self.baudcomboBox.addItem(_fromUtf8(""))
        self.baudcomboBox.addItem(_fromUtf8(""))
        self.baudcomboBox.addItem(_fromUtf8(""))
        self.baudcomboBox.addItem(_fromUtf8(""))
        self.baudcomboBox.addItem(_fromUtf8(""))
        self.baudcomboBox.addItem(_fromUtf8(""))
        self.baudcomboBox.addItem(_fromUtf8(""))
        self.baudcomboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.baudcomboBox, 5, 1, 1, 1)
        self.connectButton = QtGui.QPushButton(self.settingsTab)
        self.connectButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.connectButton.sizePolicy().hasHeightForWidth())
        self.connectButton.setSizePolicy(sizePolicy)
        self.connectButton.setMinimumSize(QtCore.QSize(200, 50))
        self.connectButton.setMaximumSize(QtCore.QSize(200, 50))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/Icons/connect.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.connectButton.setIcon(icon2)
        self.connectButton.setIconSize(QtCore.QSize(32, 32))
        self.connectButton.setObjectName(_fromUtf8("connectButton"))
        self.gridLayout.addWidget(self.connectButton, 5, 3, 1, 1)
        self.tabWidget.addTab(self.settingsTab, _fromUtf8(""))
        self.scriptTab = QtGui.QWidget()
        self.scriptTab.setObjectName(_fromUtf8("scriptTab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.scriptTab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem11, 1, 2, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem12, 1, 4, 1, 1)
        self.SendButton = QtGui.QPushButton(self.scriptTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SendButton.sizePolicy().hasHeightForWidth())
        self.SendButton.setSizePolicy(sizePolicy)
        self.SendButton.setMinimumSize(QtCore.QSize(120, 50))
        self.SendButton.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 0);"))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/Icons/running_man.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SendButton.setIcon(icon3)
        self.SendButton.setIconSize(QtCore.QSize(32, 32))
        self.SendButton.setObjectName(_fromUtf8("SendButton"))
        self.gridLayout_2.addWidget(self.SendButton, 1, 3, 1, 1)
        self.ScriptLineEdit = QtGui.QLineEdit(self.scriptTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ScriptLineEdit.sizePolicy().hasHeightForWidth())
        self.ScriptLineEdit.setSizePolicy(sizePolicy)
        self.ScriptLineEdit.setMinimumSize(QtCore.QSize(200, 50))
        self.ScriptLineEdit.setText(_fromUtf8(""))
        self.ScriptLineEdit.setObjectName(_fromUtf8("ScriptLineEdit"))
        self.gridLayout_2.addWidget(self.ScriptLineEdit, 1, 1, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem13, 1, 0, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem14, 0, 1, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem15, 2, 1, 1, 1)
        self.tabWidget.addTab(self.scriptTab, _fromUtf8(""))
        self.callTab = QtGui.QWidget()
        self.callTab.setObjectName(_fromUtf8("callTab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.callTab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        spacerItem16 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem16, 2, 3, 1, 1)
        self.Call_Button = QtGui.QPushButton(self.callTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Call_Button.sizePolicy().hasHeightForWidth())
        self.Call_Button.setSizePolicy(sizePolicy)
        self.Call_Button.setMinimumSize(QtCore.QSize(100, 50))
        self.Call_Button.setMaximumSize(QtCore.QSize(100, 50))
        self.Call_Button.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 0);"))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/Icons/unnamed.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Call_Button.setIcon(icon4)
        self.Call_Button.setIconSize(QtCore.QSize(40, 40))
        self.Call_Button.setObjectName(_fromUtf8("Call_Button"))
        self.gridLayout_3.addWidget(self.Call_Button, 1, 3, 1, 1)
        self.Halt_Button = QtGui.QPushButton(self.callTab)
        self.Halt_Button.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Halt_Button.sizePolicy().hasHeightForWidth())
        self.Halt_Button.setSizePolicy(sizePolicy)
        self.Halt_Button.setMinimumSize(QtCore.QSize(100, 50))
        self.Halt_Button.setMaximumSize(QtCore.QSize(100, 50))
        self.Halt_Button.setStyleSheet(_fromUtf8("background-color: rgb(139, 0, 0);"))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/Icons/unnamed (1).png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Halt_Button.setIcon(icon5)
        self.Halt_Button.setIconSize(QtCore.QSize(32, 32))
        self.Halt_Button.setObjectName(_fromUtf8("Halt_Button"))
        self.gridLayout_3.addWidget(self.Halt_Button, 3, 3, 1, 1)
        self.NumberlineEdit = QtGui.QLineEdit(self.callTab)
        self.NumberlineEdit.setMinimumSize(QtCore.QSize(100, 50))
        self.NumberlineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.NumberlineEdit.setMouseTracking(True)
        self.NumberlineEdit.setAcceptDrops(False)
        self.NumberlineEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.NumberlineEdit.setText(_fromUtf8(""))
        self.NumberlineEdit.setMaxLength(32767)
        self.NumberlineEdit.setFrame(True)
        self.NumberlineEdit.setEchoMode(QtGui.QLineEdit.Normal)
        self.NumberlineEdit.setCursorPosition(0)
        self.NumberlineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.NumberlineEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.NumberlineEdit.setProperty("Count", 0)
        self.NumberlineEdit.setObjectName(_fromUtf8("NumberlineEdit"))
        self.gridLayout_3.addWidget(self.NumberlineEdit, 1, 1, 1, 1)
        spacerItem17 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem17, 1, 2, 1, 1)
        spacerItem18 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem18, 1, 0, 1, 1)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem19, 1, 4, 1, 1)
        spacerItem20 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem20, 4, 3, 1, 1)
        spacerItem21 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem21, 0, 3, 1, 1)
        self.tabWidget.addTab(self.callTab, _fromUtf8(""))
        self.smsTab = QtGui.QWidget()
        self.smsTab.setObjectName(_fromUtf8("smsTab"))
        self.gridLayout_10 = QtGui.QGridLayout(self.smsTab)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.pushButton_4 = QtGui.QPushButton(self.smsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(120, 50))
        self.pushButton_4.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 0);"))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/Icons/Telegram (1).png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon6)
        self.pushButton_4.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout_10.addWidget(self.pushButton_4, 1, 5, 1, 1)
        self.label_6 = QtGui.QLabel(self.smsTab)
        self.label_6.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_10.addWidget(self.label_6, 3, 3, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.smsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(120, 50))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_10.addWidget(self.lineEdit, 3, 5, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.smsTab)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout_10.addWidget(self.lineEdit_3, 1, 3, 1, 1)
        spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem22, 1, 0, 1, 1)
        spacerItem23 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_10.addItem(spacerItem23, 0, 3, 1, 1)
        spacerItem24 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem24, 1, 4, 1, 1)
        self.plainTextEdit = QtGui.QPlainTextEdit(self.smsTab)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.gridLayout_10.addWidget(self.plainTextEdit, 4, 3, 1, 3)
        spacerItem25 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_10.addItem(spacerItem25, 5, 3, 1, 1)
        spacerItem26 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_10.addItem(spacerItem26, 2, 5, 1, 1)
        spacerItem27 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem27, 3, 4, 1, 1)
        spacerItem28 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem28, 3, 0, 1, 1)
        spacerItem29 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem29, 3, 1, 1, 1)
        self.tabWidget.addTab(self.smsTab, _fromUtf8(""))
        self.HTTP = QtGui.QWidget()
        self.HTTP.setObjectName(_fromUtf8("HTTP"))
        self.gridLayout_11 = QtGui.QGridLayout(self.HTTP)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.scrollArea_3 = QtGui.QScrollArea(self.HTTP)
        self.scrollArea_3.setStyleSheet(_fromUtf8("QScrollArea { background: transparent; }\n"
"QScrollArea > QWidget > QWidget { background: transparent; }"))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName(_fromUtf8("scrollArea_3"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 403, 529))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.gridLayout_12 = QtGui.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        spacerItem30 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_12.addItem(spacerItem30, 7, 4, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(self.scrollAreaWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(130, 50))
        self.pushButton_3.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 0);"))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/Icons/inbox-icon-46120.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon7)
        self.pushButton_3.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout_12.addWidget(self.pushButton_3, 12, 3, 1, 1)
        self.pushButton_26 = QtGui.QPushButton(self.scrollAreaWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_26.sizePolicy().hasHeightForWidth())
        self.pushButton_26.setSizePolicy(sizePolicy)
        self.pushButton_26.setMinimumSize(QtCore.QSize(130, 50))
        self.pushButton_26.setStyleSheet(_fromUtf8("background-color: rgb(139, 0, 0);"))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/Icons/Graphicloads-100-Flat-2-Outside.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_26.setIcon(icon8)
        self.pushButton_26.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_26.setObjectName(_fromUtf8("pushButton_26"))
        self.gridLayout_12.addWidget(self.pushButton_26, 2, 4, 1, 1)
        spacerItem31 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_12.addItem(spacerItem31, 13, 4, 1, 1)
        self.plainTextEdit_3 = QtGui.QPlainTextEdit(self.scrollAreaWidgetContents_3)
        self.plainTextEdit_3.setObjectName(_fromUtf8("plainTextEdit_3"))
        self.gridLayout_12.addWidget(self.plainTextEdit_3, 8, 3, 1, 2)
        spacerItem32 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_12.addItem(spacerItem32, 1, 4, 1, 1)
        self.label_2 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_2.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_12.addWidget(self.label_2, 4, 3, 1, 1)
        self.lineEdit_16 = QtGui.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.gridLayout_12.addWidget(self.lineEdit_16, 4, 4, 1, 1)
        self.label_14 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_14.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);"))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_12.addWidget(self.label_14, 6, 3, 1, 1)
        spacerItem33 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem33, 2, 5, 1, 1)
        self.pushButton_5 = QtGui.QPushButton(self.scrollAreaWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMinimumSize(QtCore.QSize(130, 50))
        self.pushButton_5.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 0);"))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/Icons/upload.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon9)
        self.pushButton_5.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout_12.addWidget(self.pushButton_5, 12, 4, 1, 1)
        spacerItem34 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_12.addItem(spacerItem34, 3, 4, 1, 1)
        self.plainTextEdit_2 = QtGui.QPlainTextEdit(self.scrollAreaWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_2.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_2.setSizePolicy(sizePolicy)
        self.plainTextEdit_2.setMinimumSize(QtCore.QSize(0, 45))
        self.plainTextEdit_2.setObjectName(_fromUtf8("plainTextEdit_2"))
        self.gridLayout_12.addWidget(self.plainTextEdit_2, 6, 4, 1, 1)
        spacerItem35 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_12.addItem(spacerItem35, 5, 4, 1, 1)
        spacerItem36 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_12.addItem(spacerItem36, 9, 3, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_11.addWidget(self.scrollArea_3, 0, 1, 1, 1)
        self.tabWidget.addTab(self.HTTP, _fromUtf8(""))
        self.TCPUDP = QtGui.QWidget()
        self.TCPUDP.setObjectName(_fromUtf8("TCPUDP"))
        self.gridLayout_9 = QtGui.QGridLayout(self.TCPUDP)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.scrollArea_2 = QtGui.QScrollArea(self.TCPUDP)
        self.scrollArea_2.setStyleSheet(_fromUtf8("QScrollArea { background: transparent; }\n"
"QScrollArea > QWidget > QWidget { background: transparent; }"))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 530, 581))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.formLayout_4 = QtGui.QFormLayout(self.scrollAreaWidgetContents_2)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_3 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_3.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.comboBox = QtGui.QComboBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(100, 50))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBox)
        self.label_4 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(200, 50))
        self.label_4.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_2 = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_5 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(200, 50))
        self.label_5.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);"))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_4 = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_4.setSizePolicy(sizePolicy)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_4)
        self.label_7 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(200, 50))
        self.label_7.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);"))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_7)
        self.lineEdit_5 = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_5.setSizePolicy(sizePolicy)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_5)
        spacerItem37 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.formLayout_4.setItem(4, QtGui.QFormLayout.FieldRole, spacerItem37)
        self.pushButton_8 = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setMinimumSize(QtCore.QSize(150, 50))
        self.pushButton_8.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 0);"))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/Icons/connect-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon10)
        self.pushButton_8.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.formLayout_4.setWidget(5, QtGui.QFormLayout.LabelRole, self.pushButton_8)
        self.pushButton_7 = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setMinimumSize(QtCore.QSize(150, 50))
        self.pushButton_7.setStyleSheet(_fromUtf8("background-color: rgb(139, 0, 0);"))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/Icons/45420.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon11)
        self.pushButton_7.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.formLayout_4.setWidget(5, QtGui.QFormLayout.FieldRole, self.pushButton_7)
        spacerItem38 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.formLayout_4.setItem(6, QtGui.QFormLayout.LabelRole, spacerItem38)
        self.plainTextEdit_7 = QtGui.QPlainTextEdit(self.scrollAreaWidgetContents_2)
        self.plainTextEdit_7.setObjectName(_fromUtf8("plainTextEdit_7"))
        self.formLayout_4.setWidget(7, QtGui.QFormLayout.SpanningRole, self.plainTextEdit_7)
        spacerItem39 = QtGui.QSpacerItem(10, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.formLayout_4.setItem(9, QtGui.QFormLayout.FieldRole, spacerItem39)
        spacerItem40 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.formLayout_4.setItem(10, QtGui.QFormLayout.LabelRole, spacerItem40)
        self.pushButton_25 = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_25.sizePolicy().hasHeightForWidth())
        self.pushButton_25.setSizePolicy(sizePolicy)
        self.pushButton_25.setMinimumSize(QtCore.QSize(150, 50))
        self.pushButton_25.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 0);"))
        self.pushButton_25.setIcon(icon6)
        self.pushButton_25.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_25.setObjectName(_fromUtf8("pushButton_25"))
        self.formLayout_4.setWidget(10, QtGui.QFormLayout.FieldRole, self.pushButton_25)
        spacerItem41 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.formLayout_4.setItem(11, QtGui.QFormLayout.FieldRole, spacerItem41)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_9.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.TCPUDP, _fromUtf8(""))
        self.FTP = QtGui.QWidget()
        self.FTP.setObjectName(_fromUtf8("FTP"))
        self.gridLayout_7 = QtGui.QGridLayout(self.FTP)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.scrollArea = QtGui.QScrollArea(self.FTP)
        self.scrollArea.setStyleSheet(_fromUtf8("QScrollArea { background: transparent; }\n"
"QScrollArea > QWidget > QWidget { background: transparent; }"))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 590, 637))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_8 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.lineEdit_6 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.gridLayout_8.addWidget(self.lineEdit_6, 1, 1, 1, 1)
        self.lineEdit_9 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.gridLayout_8.addWidget(self.lineEdit_9, 8, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);"))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_8.addWidget(self.label_9, 1, 0, 1, 1)
        self.lineEdit_7 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.gridLayout_8.addWidget(self.lineEdit_7, 2, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);"))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_8.addWidget(self.label_8, 0, 0, 1, 1)
        self.lineEdit_11 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.gridLayout_8.addWidget(self.lineEdit_11, 0, 1, 1, 1)
        self.lineEdit_10 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.gridLayout_8.addWidget(self.lineEdit_10, 9, 1, 1, 1)
        self.lineEdit_8 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.gridLayout_8.addWidget(self.lineEdit_8, 4, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);"))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_8.addWidget(self.label_11, 4, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);"))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_8.addWidget(self.label_13, 9, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);"))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_8.addWidget(self.label_12, 8, 0, 1, 1)
        self.pushButton_10 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setMinimumSize(QtCore.QSize(150, 50))
        self.pushButton_10.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 0);"))
        self.pushButton_10.setIcon(icon7)
        self.pushButton_10.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.gridLayout_8.addWidget(self.pushButton_10, 13, 0, 1, 1)
        self.plainTextEdit_4 = QtGui.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.plainTextEdit_4.setPlainText(_fromUtf8(""))
        self.plainTextEdit_4.setObjectName(_fromUtf8("plainTextEdit_4"))
        self.gridLayout_8.addWidget(self.plainTextEdit_4, 10, 0, 3, 2)
        self.pushButton_9 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setMinimumSize(QtCore.QSize(150, 50))
        self.pushButton_9.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 0);"))
        self.pushButton_9.setIcon(icon9)
        self.pushButton_9.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.gridLayout_8.addWidget(self.pushButton_9, 13, 1, 1, 1)
        spacerItem42 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem42, 4, 2, 1, 1)
        spacerItem43 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_8.addItem(spacerItem43, 5, 1, 1, 1)
        spacerItem44 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_8.addItem(spacerItem44, 14, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);"))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_8.addWidget(self.label_10, 2, 0, 1, 1)
        self.widget = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_6 = QtGui.QGridLayout(self.widget)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.pushButton_12 = QtGui.QPushButton(self.widget)
        self.pushButton_12.setMinimumSize(QtCore.QSize(150, 50))
        self.pushButton_12.setStyleSheet(_fromUtf8("background-color: rgb(139, 0, 0);"))
        self.pushButton_12.setIcon(icon11)
        self.pushButton_12.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.gridLayout_6.addWidget(self.pushButton_12, 0, 2, 2, 1)
        self.pushButton_11 = QtGui.QPushButton(self.widget)
        self.pushButton_11.setMinimumSize(QtCore.QSize(150, 50))
        self.pushButton_11.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_11.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 0);"))
        self.pushButton_11.setIcon(icon10)
        self.pushButton_11.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.gridLayout_6.addWidget(self.pushButton_11, 0, 0, 2, 1)
        spacerItem45 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem45, 0, 1, 1, 1)
        self.gridLayout_8.addWidget(self.widget, 7, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_7.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidget.addTab(self.FTP, _fromUtf8(""))
        self.gridLayout_5.addWidget(self.tabWidget, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setCheckable(True)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon12)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionNew = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/New.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon13)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Elementz_GSM_Utility", None))
        self.pushButton_6.setText(_translate("MainWindow", "Clear Log", None))
        self.SerialConsole.setToolTip(_translate("MainWindow", "Serial Console is readonly!!", None))
        self.SerialConsole.setPlainText(_translate("MainWindow", "Serial Console", None))
        self.label.setText(_translate("MainWindow", "Serial Terminal", None))
        self.findButton.setText(_translate("MainWindow", "Find Port", None))
        self.portComboBox.setToolTip(_translate("MainWindow", "Select COM Port", None))
        self.baudcomboBox.setToolTip(_translate("MainWindow", "Select BAUD Rate", None))
        self.baudcomboBox.setItemText(0, _translate("MainWindow", "SELECT", None))
        self.baudcomboBox.setItemText(1, _translate("MainWindow", "300", None))
        self.baudcomboBox.setItemText(2, _translate("MainWindow", "600", None))
        self.baudcomboBox.setItemText(3, _translate("MainWindow", "1200", None))
        self.baudcomboBox.setItemText(4, _translate("MainWindow", "2400", None))
        self.baudcomboBox.setItemText(5, _translate("MainWindow", "4800", None))
        self.baudcomboBox.setItemText(6, _translate("MainWindow", "9600", None))
        self.baudcomboBox.setItemText(7, _translate("MainWindow", "19200", None))
        self.baudcomboBox.setItemText(8, _translate("MainWindow", "38400", None))
        self.baudcomboBox.setItemText(9, _translate("MainWindow", "57600", None))
        self.baudcomboBox.setItemText(10, _translate("MainWindow", "115200", None))
        self.connectButton.setText(_translate("MainWindow", "Connect", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settingsTab), _translate("MainWindow", "Settings", None))
        self.SendButton.setText(_translate("MainWindow", "Execute", None))
        self.ScriptLineEdit.setToolTip(_translate("MainWindow", "Type AT command and press Send Button, eg: AT+CSQ", None))
        self.ScriptLineEdit.setPlaceholderText(_translate("MainWindow", "Eg: AT+CSQ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.scriptTab), _translate("MainWindow", "Geek Mode", None))
        self.Call_Button.setText(_translate("MainWindow", "Call", None))
        self.Halt_Button.setText(_translate("MainWindow", "End Call", None))
        self.NumberlineEdit.setToolTip(_translate("MainWindow", "Type phone number and press Call, eg: 09495XXXXXX", None))
        self.NumberlineEdit.setPlaceholderText(_translate("MainWindow", "EX:944XXXXXXXX", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.callTab), _translate("MainWindow", "Call", None))
        self.pushButton_4.setText(_translate("MainWindow", "Send", None))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">No of Characters Entered :</p></body></html>", None))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "EX : 944XXXXXXX", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.smsTab), _translate("MainWindow", "SMS", None))
        self.pushButton_3.setText(_translate("MainWindow", "GET", None))
        self.pushButton_26.setText(_translate("MainWindow", "Close Session", None))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">APN Name:</p></body></html>", None))
        self.lineEdit_16.setPlaceholderText(_translate("MainWindow", "No Need to Type if u Have Already Typed", None))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Source Address :</p></body></html>", None))
        self.pushButton_5.setText(_translate("MainWindow", "POST", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.HTTP), _translate("MainWindow", "http", None))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" color:#ffffff;\">Choose Your Preference :</span></p></body></html>", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "Select", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "TCP", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "UDP", None))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" color:#ffffff;\">APN Name :</span></p></body></html>", None))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "No Need to Type if You have Already Typed", None))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" color:#ffffff;\">Server IP :</span></p></body></html>", None))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" color:#ffffff;\">Port No :</span></p></body></html>", None))
        self.pushButton_8.setText(_translate("MainWindow", "Connect", None))
        self.pushButton_7.setText(_translate("MainWindow", "Disconnect", None))
        self.pushButton_25.setText(_translate("MainWindow", "Send", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TCPUDP), _translate("MainWindow", "TCP/ UDP", None))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" color:#ffffff;\">FTP Server :</span></p></body></html>", None))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" color:#ffffff;\">APN Name :</span></p></body></html>", None))
        self.lineEdit_11.setPlaceholderText(_translate("MainWindow", "Already Typed?No Need To Type Again", None))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" color:#ffffff;\">Password :</span></p></body></html>", None))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" color:#ffffff;\">Directry :</span></p></body></html>", None))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" color:#ffffff;\">File Name :</span></p></body></html>", None))
        self.pushButton_10.setText(_translate("MainWindow", "FTP Get", None))
        self.pushButton_9.setText(_translate("MainWindow", "FTP Push", None))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" color:#ffffff;\">Username :</span></p></body></html>", None))
        self.pushButton_12.setText(_translate("MainWindow", "Disconnect", None))
        self.pushButton_11.setText(_translate("MainWindow", "Connect", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.FTP), _translate("MainWindow", "FTP", None))
        self.actionSave.setText(_translate("MainWindow", "&Save", None))
        self.actionSave.setToolTip(_translate("MainWindow", "Save", None))
        self.actionNew.setText(_translate("MainWindow", "&New", None))
        self.actionOpen.setText(_translate("MainWindow", "&Open", None))

import background_rc
