# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GSMUtility.ui'
#
# Created: Wed Jun 08 13:22:13 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(792, 372)
        MainWindow.setStyleSheet(_fromUtf8("QMainWindow{background-image: url(:/Background/Icons/background.jpg);background-repeat: repeat;}\n"
"\n"
"QToolBar{background:blue;}\n"
"\n"
"QWidget#tabWidget{background-color: blue;}\n"
"QTabBar::tab { background: darkblue; color: white; padding: 10px; border: 2px solid blue;}\n"
"QTabBar::tab:selected {background: rgb(217, 217, 0);  color: black; }\n"
"QTabBar::tab:!selected {background:darkblue;  color: white;}\n"
"/*QTabBar {background-color: blue;} */\n"
"QTabBar::tab:hover{color:#ccc;    background-color: qlineargradient(spread:pad, x1:0.517, y1:0, x2:0.517, y2:1, stop:0 rgba(45, 45, 45, 255), stop:0.505682 rgba(45, 45, 45, 255), stop:1 rgba(29, 29, 29, 255));    border-color:#2d89ef;border-width:2px;}\n"
"\n"
"QPushButton{border-style:solid;background-color:darkblue;color:white;border-radius:3px;font: 12pt \"MS Shell Dlg 2\";}\n"
"QPushButton:hover{color:#ccc;    background-color: qlineargradient(spread:pad, x1:0.517, y1:0, x2:0.517, y2:1, stop:0 rgba(45, 45, 45, 255), stop:0.505682 rgba(45, 45, 45, 255), stop:1 rgba(29, 29, 29, 255));    border-color:#2d89ef;border-width:2px;}\n"
"QPushButton:pressed{background-color: lightblue;}\n"
"QPushButton:disabled{background-color: rgb(176, 176, 176);}\n"
"\n"
"QPushButton#connectButton{ background-color: darkred;}\n"
"QPushButton#connectButton:hover{color:#ccc;    background-color: qlineargradient(spread:pad, x1:0.517, y1:0, x2:0.517, y2:1, stop:0 rgba(45, 45, 45, 255), stop:0.505682 rgba(45, 45, 45, 255), stop:1 rgba(29, 29, 29, 255));    border-color:#2d89ef;border-width:2px;}\n"
"QPushButton#connectButton:pressed{background-color: lightblue;}\n"
"QPushButton#connectButton:disabled{background-color: rgb(176, 176, 176);}\n"
"\n"
"QComboBox{border-style:solid;background-color:darkblue;color:white;border-radius:3px;font: 12pt \"MS Shell Dlg 2\"; padding: 10px}\n"
"QComboBox:hover{color:#ccc;    background-color: qlineargradient(spread:pad, x1:0.517, y1:0, x2:0.517, y2:1, stop:0 rgba(45, 45, 45, 255), stop:0.505682 rgba(45, 45, 45, 255), stop:1 rgba(29, 29, 29, 255));    border-color:#2d89ef;border-width:2px;}\n"
"QComboBox:pressed{background-color: lightblue;}\n"
"\n"
"QLineEdit {border:4px outset; border-radius: 8px; border-color: blue; color:rgb(0, 0, 0);  background-color: rgb(235, 235, 235); padding:10px;font: 75 12pt \"MS Shell Dlg 2\";}\n"
"/*QLineEdit { border-radius: 8px;  color:black;background-color: white; } */\n"
"QLineEdit:focus {  border:4px outset; border-radius: 8px; border-color: rgb(41, 237, 215); color:rgb(0, 0, 0);  background-color: rgb(240, 204, 204); }\n"
"\n"
"QLabel {border:4px outset; border-radius: 0px; border-color: blue; color:white;  background-color: darkblue; padding:5px;font: 75 12pt \"MS Shell Dlg 2\";}\n"
"QPlainTextEdit {border:4px outset; border-radius: 0px; border-color: blue; color:black;  background-color: rgb(235, 235, 235);; padding:5px;font: 75 12pt \"MS Shell Dlg 2\";}"))
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_5 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setToolTip(_fromUtf8(""))
        self.tabWidget.setStatusTip(_fromUtf8(""))
        self.tabWidget.setWhatsThis(_fromUtf8(""))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet(_fromUtf8(""))
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.settingsTab = QtGui.QWidget()
        self.settingsTab.setObjectName(_fromUtf8("settingsTab"))
        self.gridLayout = QtGui.QGridLayout(self.settingsTab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(20, 60, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 6, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 5, 0, 1, 1)
        self.connectButton = QtGui.QPushButton(self.settingsTab)
        self.connectButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.connectButton.sizePolicy().hasHeightForWidth())
        self.connectButton.setSizePolicy(sizePolicy)
        self.connectButton.setMinimumSize(QtCore.QSize(200, 50))
        self.connectButton.setMaximumSize(QtCore.QSize(200, 50))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/connect.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.connectButton.setIcon(icon)
        self.connectButton.setIconSize(QtCore.QSize(32, 32))
        self.connectButton.setObjectName(_fromUtf8("connectButton"))
        self.gridLayout.addWidget(self.connectButton, 5, 3, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 5, 2, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(132, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 5, 4, 1, 1)
        self.findButton = QtGui.QPushButton(self.settingsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.findButton.sizePolicy().hasHeightForWidth())
        self.findButton.setSizePolicy(sizePolicy)
        self.findButton.setMinimumSize(QtCore.QSize(200, 50))
        self.findButton.setMaximumSize(QtCore.QSize(200, 50))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/find.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.findButton.setIcon(icon1)
        self.findButton.setIconSize(QtCore.QSize(32, 32))
        self.findButton.setObjectName(_fromUtf8("findButton"))
        self.gridLayout.addWidget(self.findButton, 2, 3, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(10, 10, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 2, 2, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 2, 4, 1, 1)
        self.portComboBox = QtGui.QComboBox(self.settingsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portComboBox.sizePolicy().hasHeightForWidth())
        self.portComboBox.setSizePolicy(sizePolicy)
        self.portComboBox.setMinimumSize(QtCore.QSize(200, 50))
        self.portComboBox.setMaximumSize(QtCore.QSize(200, 50))
        self.portComboBox.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContentsOnFirstShow)
        self.portComboBox.setObjectName(_fromUtf8("portComboBox"))
        self.gridLayout.addWidget(self.portComboBox, 2, 1, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(10, 10, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 2, 0, 1, 1)
        self.baudcomboBox = QtGui.QComboBox(self.settingsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baudcomboBox.sizePolicy().hasHeightForWidth())
        self.baudcomboBox.setSizePolicy(sizePolicy)
        self.baudcomboBox.setMinimumSize(QtCore.QSize(200, 50))
        self.baudcomboBox.setMaximumSize(QtCore.QSize(200, 50))
        self.baudcomboBox.setObjectName(_fromUtf8("baudcomboBox"))
        self.baudcomboBox.addItem(_fromUtf8(""))
        self.baudcomboBox.addItem(_fromUtf8(""))
        self.baudcomboBox.addItem(_fromUtf8(""))
        self.baudcomboBox.addItem(_fromUtf8(""))
        self.baudcomboBox.addItem(_fromUtf8(""))
        self.baudcomboBox.addItem(_fromUtf8(""))
        self.baudcomboBox.addItem(_fromUtf8(""))
        self.baudcomboBox.addItem(_fromUtf8(""))
        self.baudcomboBox.addItem(_fromUtf8(""))
        self.baudcomboBox.addItem(_fromUtf8(""))
        self.baudcomboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.baudcomboBox, 5, 1, 1, 1)
        self.tabWidget.addTab(self.settingsTab, _fromUtf8(""))
        self.scriptTab = QtGui.QWidget()
        self.scriptTab.setObjectName(_fromUtf8("scriptTab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.scriptTab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.SendButton = QtGui.QPushButton(self.scriptTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SendButton.sizePolicy().hasHeightForWidth())
        self.SendButton.setSizePolicy(sizePolicy)
        self.SendButton.setMinimumSize(QtCore.QSize(100, 50))
        self.SendButton.setObjectName(_fromUtf8("SendButton"))
        self.gridLayout_2.addWidget(self.SendButton, 1, 3, 1, 1)
        self.ScriptLineEdit = QtGui.QLineEdit(self.scriptTab)
        self.ScriptLineEdit.setMinimumSize(QtCore.QSize(250, 50))
        self.ScriptLineEdit.setText(_fromUtf8(""))
        self.ScriptLineEdit.setObjectName(_fromUtf8("ScriptLineEdit"))
        self.gridLayout_2.addWidget(self.ScriptLineEdit, 1, 1, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 1, 2, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem10, 1, 4, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem11, 0, 1, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem12, 2, 1, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem13, 1, 0, 1, 1)
        self.tabWidget.addTab(self.scriptTab, _fromUtf8(""))
        self.callTab = QtGui.QWidget()
        self.callTab.setObjectName(_fromUtf8("callTab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.callTab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem14, 2, 3, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.callTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(100, 50))
        self.pushButton_2.setMaximumSize(QtCore.QSize(100, 50))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_3.addWidget(self.pushButton_2, 1, 3, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(self.callTab)
        self.pushButton_3.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(100, 50))
        self.pushButton_3.setMaximumSize(QtCore.QSize(100, 50))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout_3.addWidget(self.pushButton_3, 3, 3, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.callTab)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(100, 50))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_2.setText(_fromUtf8(""))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout_3.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem15, 1, 2, 1, 1)
        spacerItem16 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem16, 1, 0, 1, 1)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem17, 1, 4, 1, 1)
        spacerItem18 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem18, 4, 3, 1, 1)
        spacerItem19 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem19, 0, 3, 1, 1)
        self.tabWidget.addTab(self.callTab, _fromUtf8(""))
        self.smsTab = QtGui.QWidget()
        self.smsTab.setObjectName(_fromUtf8("smsTab"))
        self.gridLayout_4 = QtGui.QGridLayout(self.smsTab)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        spacerItem20 = QtGui.QSpacerItem(10, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem20, 2, 1, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(self.smsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(100, 50))
        self.pushButton_4.setMaximumSize(QtCore.QSize(100, 50))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout_4.addWidget(self.pushButton_4, 1, 3, 1, 1)
        spacerItem21 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem21, 1, 0, 1, 1)
        spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem22, 1, 4, 1, 1)
        spacerItem23 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem23, 1, 2, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.smsTab)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(100, 50))
        self.lineEdit_3.setStatusTip(_fromUtf8(""))
        self.lineEdit_3.setText(_fromUtf8(""))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout_4.addWidget(self.lineEdit_3, 1, 1, 1, 1)
        spacerItem24 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem24, 4, 1, 1, 1)
        spacerItem25 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem25, 0, 1, 1, 1)
        self.plainTextEdit = QtGui.QPlainTextEdit(self.smsTab)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.gridLayout_4.addWidget(self.plainTextEdit, 3, 1, 1, 1)
        self.tabWidget.addTab(self.smsTab, _fromUtf8(""))
        self.gridLayout_5.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_5.addWidget(self.label, 0, 1, 1, 1)
        self.SerialConsole = QtGui.QPlainTextEdit(self.centralwidget)
        self.SerialConsole.setMinimumSize(QtCore.QSize(300, 0))
        self.SerialConsole.setReadOnly(True)
        self.SerialConsole.setObjectName(_fromUtf8("SerialConsole"))
        self.gridLayout_5.addWidget(self.SerialConsole, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setCheckable(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon2)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionNew = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/New.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon3)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionOpen = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon4)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.connectButton.setText(_translate("MainWindow", "Connect", None))
        self.findButton.setText(_translate("MainWindow", "Find Port", None))
        self.portComboBox.setToolTip(_translate("MainWindow", "Select COM Port", None))
        self.baudcomboBox.setToolTip(_translate("MainWindow", "Select BAUD Rate", None))
        self.baudcomboBox.setItemText(0, _translate("MainWindow", "SELECT", None))
        self.baudcomboBox.setItemText(1, _translate("MainWindow", "300", None))
        self.baudcomboBox.setItemText(2, _translate("MainWindow", "600", None))
        self.baudcomboBox.setItemText(3, _translate("MainWindow", "1200", None))
        self.baudcomboBox.setItemText(4, _translate("MainWindow", "2400", None))
        self.baudcomboBox.setItemText(5, _translate("MainWindow", "4800", None))
        self.baudcomboBox.setItemText(6, _translate("MainWindow", "9600", None))
        self.baudcomboBox.setItemText(7, _translate("MainWindow", "19200", None))
        self.baudcomboBox.setItemText(8, _translate("MainWindow", "38400", None))
        self.baudcomboBox.setItemText(9, _translate("MainWindow", "57600", None))
        self.baudcomboBox.setItemText(10, _translate("MainWindow", "115200", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settingsTab), _translate("MainWindow", "Settings", None))
        self.SendButton.setText(_translate("MainWindow", "Send", None))
        self.ScriptLineEdit.setToolTip(_translate("MainWindow", "Type AT command and press Send Button, eg: AT+CSQ", None))
        self.ScriptLineEdit.setPlaceholderText(_translate("MainWindow", "Eg: AT+CSQ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.scriptTab), _translate("MainWindow", "AT Script", None))
        self.pushButton_2.setText(_translate("MainWindow", "Call", None))
        self.pushButton_3.setText(_translate("MainWindow", "Halt", None))
        self.lineEdit_2.setToolTip(_translate("MainWindow", "Type phone number and press Call, eg: 09495XXXXXX", None))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Eg: 09495XXXXXX", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.callTab), _translate("MainWindow", "Call", None))
        self.pushButton_4.setText(_translate("MainWindow", "Send", None))
        self.lineEdit_3.setToolTip(_translate("MainWindow", "Enter phone number, Write message below and Press Send button", None))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Eg: 9495XXXXXX", None))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "Type your Message Here!", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.smsTab), _translate("MainWindow", "SMS", None))
        self.label.setText(_translate("MainWindow", "Serial Terminal", None))
        self.SerialConsole.setToolTip(_translate("MainWindow", "Serial Console is readonly!!", None))
        self.SerialConsole.setPlainText(_translate("MainWindow", "Serial Console", None))
        self.actionSave.setText(_translate("MainWindow", "&Save", None))
        self.actionSave.setToolTip(_translate("MainWindow", "Save", None))
        self.actionNew.setText(_translate("MainWindow", "&New", None))
        self.actionOpen.setText(_translate("MainWindow", "&Open", None))

import background_rc
